### ISSUE TITLE
运行环境

### ISSUE THREAD

**Issue by caiyinqiong** [jingtaozhan/RepBERT-Index#1]
请问一下你的基本运行环境是怎么样的，比如torch和transformers的版本？谢谢。

**Comment by jingtaozhan** [comment]
Try transformers==2.10.0 and torch==1.6.0 and see whether it works.

**Comment by caiyinqiong** [comment]
If I use 2 gpus, it reports an error. Can you help me to resolve it, thx~ (I use the transformers==2.10.0 and torch==1.6.0)
---------------------------------------------------------------------------------------
Iteration:   0%|                                                                                                                                                                                                                                 | 0/1038150 [00:03<?, ?it/s]
Epoch:   0%|                                                                                                                                                                                                                                          | 0/10 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "./train.py", line 255, in <module>
    main()
  File "./train.py", line 247, in main
    train(args, model)
  File "./train.py", line 97, in train
    outputs = model(**batch)
  File "/data/users/caiyinqiong/anaconda3/envs/marco/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/users/caiyinqiong/anaconda3/envs/marco/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/data/users/caiyinqiong/anaconda3/envs/marco/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/data/users/caiyinqiong/anaconda3/envs/marco/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/data/users/caiyinqiong/anaconda3/envs/marco/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/data/users/caiyinqiong/anaconda3/envs/marco/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/data/users/caiyinqiong/anaconda3/envs/marco/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/users/caiyinqiong/marco-exp/RepBERT-Index/modeling.py", line 60, in forward
    loss = loss_fct(similarities, labels)
  File "/data/users/caiyinqiong/anaconda3/envs/marco/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/users/caiyinqiong/anaconda3/envs/marco/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 755, in forward
    return F.multilabel_margin_loss(input, target, reduction=self.reduction)
  File "/data/users/caiyinqiong/anaconda3/envs/marco/lib/python3.6/site-packages/torch/nn/functional.py", line 2711, in multilabel_margin_loss
    return torch._C._nn.multilabel_margin_loss(input, target, reduction_enum)
RuntimeError: inconsistent target size: [26, 52] for input of size: [26, 26]

**Comment by jingtaozhan** [comment]
This is caused by the in-batch trick. When you use multiple gpus, the batch is splitted and but the labels are not. 
Maybe compute the loss after the model returns the result or split the labels in advance can solve it.
